before_install:
 - sudo add-apt-repository ppa:trevorbernard/zeromq -y
 - sudo apt-get update -y
 - sudo apt-get install libzmq2-dev libpgm-dev make build-essential pkg-config libtool automake -y
- git clone git://github.com/jedisct1/libsodium.git
- cd libsodium
- git checkout 0.4.5
- ./autogen.sh
- ./configure && make check
- sudo make install
- sudo ldconfig
- cd ..
 - ./autogen.sh
 - ./configure
 - make
 - sudo make install
install: mvn install --quiet -DskipTests=true -Dgpg.skip=true
language: java

script: mvn test

jdk:
 - openjdk6
 - openjdk7
